import json

with open("kaps_iter.json","w") as f:
    f.write('{')
    f.write('\n\t')
    f.write('"class_name": "GridlabBusParams",')
    f.write('\n\t')
    f.write('"bus_type": "GridlabBus",')
    f.write('\n\t')
    f.write('"filename": "act_pow_main.glm",')
    f.write('\n\t')
    f.write('"time_info": {')
    f.write('\n\t\t')
    f.write('"start": "2000-01-01 00:00:00",')
    f.write('\n\t\t')
    f.write('"delta": 900,')
    f.write('\n\t\t')
    f.write('"end": "2100-01-01 00:00:00"')
    f.write('\n\t')
    f.write('},')
    f.write('\n\t')
    f.write('"output": [\n')
    for i in range(1,13):
        f.write('\t\t{\n\t')
        f.write('"name": "PV_N6A_DH%d",'%i)
        f.write('\n\t')
        f.write('"param": "measured_voltage_A",')
        f.write('\n\t')
        f.write('"param": "measured_power_A"')
        if i == 12:
            f.write('\n\t\t}\n')
        else:
            f.write('\n\t\t},\n')
    f.write('\n\n\t],\n\t')
    f.write('"poll": 0.05,\n\t')
    f.write('"debug":false,\n\t')
    f.write('"debug_type": "dNone"\n}')
        
with open("kaps_main.json","w") as f:
    f.write('{')
    f.write('\n\t')
    f.write('"class_name": "GridlabBusParams",')
    f.write('\n\t')
    f.write('"bus_type": "GridlabBus",')
    f.write('\n\t')
    f.write('"filename": "act_pow_main.glm",')
    f.write('\n\t')
    f.write('"time_info": {')
    f.write('\n\t\t')
    f.write('"start": "2014-06-22 00:00:00",')
    f.write('\n\t\t')
    f.write('"delta": 60,')
    f.write('\n\t\t')
    f.write('"end": "2014-06-22 23:59:00"')
    f.write('\n\t')
    f.write('},')
    f.write('\n\t')
    f.write('"output": [\n')
    for i in range(1,13):
        f.write('\t\t{\n\t')
        f.write('"name": "PV_N6A_DH%d",'%i)
        f.write('\n\t')
        f.write('"param": "measured_voltage_A",')
        f.write('\n\t')
        f.write('"param": "measured_power_A"')
        if i == 12:
            f.write('\n\t\t}\n')
        else:
            f.write('\n\t\t},\n')
    f.write('\n\n\t],\n\t')
    f.write('"poll": 0.05,\n\t')
    f.write('"debug":false,\n\t')
    f.write('"debug_type": "dNone"\n}')
